services:
  mongodb_container:
    image: mongo:latest  # Corrigido o nome e a tag da imagem
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db  # Associando o volume

volumes:
  mongodb_data_container:  # Declarando o volume
